export const GET_CHAT_LIST_FOR_USER = 'GET_CHAT_LIST_FOR_USER';
export const GET_DIRECT_MESSAGE_CHAT = 'GET_DIRECT_MESSAGE_CHAT';
export const GET_GROUP_CHAT = 'GET_GROUP_CHAT';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const GET_ALL_USERS = 'GET_ALL_USERS';
export const SET_USER = 'SET_USER';